server:
  port: 8081
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 10.43.78.200
    # Redis端口
    port: 6399
    # Redis密码
    password: 123456
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    connect-timeout: 1000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.43.78.200:3366/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.qax.model
logging:
  level:
    com.qax.mapper: debug
