-- auto Generated on 2021-01-05
DROP TABLE IF EXISTS t_person;
CREATE TABLE t_person(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	role_acc VARCHAR (50) NOT NULL DEFAULT '' COMMENT '角色账户',
	role_code VARCHAR (50) NOT NULL DEFAULT '' COMMENT '角色代码',
	role_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT '角色名称',
	date_created DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '创建时间',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'persion';
